Enhance AdGuard Home init script with new features
Enhanced the AdGuard Home init script with additional commands for configuration management and cron job handling.

diff --git a/patches/01_init.patch b/patches/01_init.patch
--- a/patches/01_init.patch
+++ b/patches/01_init.patch
@@ -5,8 +5,8 @@ Subject: [PATCH] Enhance AdGuard Home init script with new features
 
 Added extra commands and functions for configuration management and cron job handling in AdGuard Home init script.
 ---
- root/etc/init.d/adguardhome | 171 +++++++++++++++++++++++++++++++++++-
- 1 file changed, 169 insertions(+), 2 deletions(-)
+ root/etc/init.d/adguardhome | 181 +++++++++++++++++++++++++++++++++++-
+ 1 file changed, 179 insertions(+), 2 deletions(-)
 
 diff --git a/root/etc/init.d/adguardhome b/root/etc/init.d/adguardhome
 index 4712913..384239c 100755
@@ -116,7 +116,7 @@ index 4712913..384239c 100755
  
  	uci_validate_section 'adguardhome' 'adguardhome' "$config_name" \
  		'gc:uinteger:0' \
-@@ -41,12 +126,32 @@ start_service() {
+@@ -41,12 +126,42 @@ start_service() {
  		'user:string:adguardhome' \
  		'verbose:bool:0' \
  		'workdir:string' \
@@ -147,10 +147,20 @@ index 4712913..384239c 100755
 +		return 0
 +	fi
 +
++	if [ "$user" = "adguardhome" ] && ! grep -q "^adguardhome:" /etc/passwd; then
++		echo "luci-app: User 'adguardhome' is missing, injecting UID 853 into system files..." >&2
++
++		# 1. 确保组存在，不存在则直接追加
++		grep -q "^adguardhome:" /etc/group || echo "adguardhome:x:853:" >> /etc/group
++
++		# 2. 直接向 passwd 追加用户（严格对应你 EQ12 上的标准格式）
++		echo "adguardhome:x:853:853:adguardhome:/var/run/adguardhome:/bin/false" >> /etc/passwd
++	fi
++
  	local config_dir
  	config_dir=$(dirname "$config_file")
  	if [ "$config_dir" = '/etc' ]; then
-@@ -59,6 +164,13 @@ start_service() {
+@@ -59,6 +174,13 @@ start_service() {
  	mkdir -m 0700 -p "$work_dir"
  	chown -R "$user":"$group" "$work_dir"
  
@@ -164,7 +174,7 @@ index 4712913..384239c 100755
  	procd_open_instance adguardhome
  
  	procd_set_param command "$PROG"
-@@ -67,9 +179,14 @@ start_service() {
+@@ -67,9 +189,14 @@ start_service() {
  	[ "$maxprocs" -le 0 ] || procd_append_param env GOMAXPROCS="$maxprocs"
  	[ "$memlimit" -le 0 ] || procd_append_param env GOMEMLIMIT="$memlimit"
  
@@ -180,7 +190,7 @@ index 4712913..384239c 100755
  	[ "$verbose" = 1 ] && procd_append_param command --verbose
  	procd_append_param command --work-dir "$work_dir"
  
-@@ -91,10 +208,60 @@ start_service() {
+@@ -91,10 +218,60 @@ start_service() {
  
  	procd_add_jail_mount '/etc/hosts'
  	procd_add_jail_mount '/etc/ssl/certs'
@@ -207,7 +217,7 @@ index 4712913..384239c 100755
 +	(sleep 10 && [ -z "$(pgrep -f "$(basename "$PROG")")" ] && logger -t adguardhome "no process in 10s cancel redirect" && $CONTROL_SCRIPT 0 ) &
 +}
 +
-+# 必须注入显式的服务中止钩子，用于平滑清理 nft 规则和 crontab
++# 必须注入显式的服务中止钩子，用于平滑清理 nft 规则 and crontab
 +stop_service() {
 +	config_load 'adguardhome'
 +	local config_name='config'
